// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoVIS.Data;

#nullable disable

namespace TechnoVIS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803204448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnoVIS.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Bd Zerktouni, Casablanca",
                            CodeClient = "CL-001",
                            ContactPrincipal = "Karim Benali",
                            Email = "k.benali@totalenergies.ma",
                            NomSociete = "TotalEnergies Maroc",
                            Telephone = "+212 522 10 20 30"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Zone Industrielle, Safi",
                            CodeClient = "CL-002",
                            ContactPrincipal = "Sarah Mansouri",
                            Email = "s.mansouri@ocpgroup.ma",
                            NomSociete = "OCP Group Safi",
                            Telephone = "+212 524 88 99 00"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Sidi Maârouf, Casablanca",
                            CodeClient = "CL-003",
                            ContactPrincipal = "Youssef Tazi",
                            Email = "y.tazi@attijariwafa.com",
                            NomSociete = "Attijariwafa Data Center",
                            Telephone = "+212 522 45 67 89"
                        });
                });

            modelBuilder.Entity("TechnoVIS.Models.Equipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Criticiticite")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateInstallation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DerniereVisite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProchaineVisitePrevue")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScoreRisque")
                        .HasColumnType("int");

                    b.Property<int>("ScoreSante")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Equipements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "HVAC",
                            Criticiticite = 5,
                            DateInstallation = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DerniereVisite = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Groupe Froid Trane Centravac",
                            ProchaineVisitePrevue = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScoreRisque = 38,
                            ScoreSante = 78,
                            SerialNumber = "EQ-HVAC-901",
                            SiteId = 1,
                            Statut = "Opérationnel"
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Groupe Électrogène",
                            Criticiticite = 5,
                            DateInstallation = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DerniereVisite = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Groupe Électrogène Caterpillar 1500kVA",
                            ProchaineVisitePrevue = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScoreRisque = 74,
                            ScoreSante = 62,
                            SerialNumber = "EQ-GE-404",
                            SiteId = 3,
                            Statut = "Maintenance Requise"
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Transformateur",
                            Criticiticite = 4,
                            DateInstallation = new DateTime(2018, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DerniereVisite = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Transformateur Schneider Triphasé 20kV",
                            ProchaineVisitePrevue = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScoreRisque = 18,
                            ScoreSante = 91,
                            SerialNumber = "EQ-TRF-208",
                            SiteId = 2,
                            Statut = "Opérationnel"
                        },
                        new
                        {
                            Id = 4,
                            Categorie = "Compresseur",
                            Criticiticite = 3,
                            DateInstallation = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DerniereVisite = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Compresseur Atlas Copco GA75",
                            ProchaineVisitePrevue = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScoreRisque = 22,
                            ScoreSante = 85,
                            SerialNumber = "EQ-CMP-302",
                            SiteId = 2,
                            Statut = "Opérationnel"
                        },
                        new
                        {
                            Id = 5,
                            Categorie = "TGBT",
                            Criticiticite = 5,
                            DateInstallation = new DateTime(2017, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DerniereVisite = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Armoire TGBT Principal Masterpact",
                            ProchaineVisitePrevue = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScoreRisque = 82,
                            ScoreSante = 55,
                            SerialNumber = "EQ-TGBT-101",
                            SiteId = 1,
                            Statut = "En Révision"
                        });
                });

            modelBuilder.Entity("TechnoVIS.Models.Marche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CodeMarche")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlaHeures")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitesAnnuellesPrevues")
                        .HasColumnType("int");

                    b.Property<int>("VisitesRealisees")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Marches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CodeMarche = "MAR-2026-089",
                            DateDebut = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Maintenance Préventive HVAC & Groupes Électrogènes",
                            SlaHeures = 12,
                            Statut = "Actif",
                            VisitesAnnuellesPrevues = 24,
                            VisitesRealisees = 14
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CodeMarche = "MAR-2026-112",
                            DateDebut = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2027, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Maintenance Haute Tension & Transformateurs",
                            SlaHeures = 4,
                            Statut = "Actif",
                            VisitesAnnuellesPrevues = 48,
                            VisitesRealisees = 32
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            CodeMarche = "MAR-2026-045",
                            DateDebut = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2027, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Audit & Maintenance Datacenter",
                            SlaHeures = 2,
                            Statut = "Actif",
                            VisitesAnnuellesPrevues = 52,
                            VisitesRealisees = 20
                        });
                });

            modelBuilder.Entity("TechnoVIS.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NomSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Tour Total, Anfa",
                            ClientId = 1,
                            CodePostal = "20000",
                            CodeSite = "ST-CAS-01",
                            Latitude = 33.589886,
                            Longitude = -7.6038690000000004,
                            NomSite = "Siège Social Casablanca",
                            Ville = "Casablanca"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Km 9 Route d'El Jadida",
                            ClientId = 2,
                            CodePostal = "46000",
                            CodeSite = "ST-SAF-02",
                            Latitude = 32.299388999999998,
                            Longitude = -9.2371809999999996,
                            NomSite = "Complexe Chimique Safi",
                            Ville = "Safi"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Parc Technologique",
                            ClientId = 3,
                            CodePostal = "20650",
                            CodeSite = "ST-CAS-02",
                            Latitude = 33.549999999999997,
                            Longitude = -7.483333,
                            NomSite = "Datacenter Tit Mellil",
                            Ville = "Casablanca"
                        });
                });

            modelBuilder.Entity("TechnoVIS.Models.Technicien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargeActuelle")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteRattacheId")
                        .HasColumnType("int");

                    b.Property<string>("Specialites")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteRattacheId");

                    b.ToTable("Techniciens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChargeActuelle = 3,
                            Disponible = true,
                            Nom = "El Amrani",
                            Prenom = "Amine",
                            SiteRattacheId = 1,
                            Specialites = "HVAC,TGBT"
                        },
                        new
                        {
                            Id = 2,
                            ChargeActuelle = 5,
                            Disponible = true,
                            Nom = "Chraibi",
                            Prenom = "Hassan",
                            SiteRattacheId = 3,
                            Specialites = "Groupe Électrogène,Compresseur"
                        },
                        new
                        {
                            Id = 3,
                            ChargeActuelle = 1,
                            Disponible = true,
                            Nom = "Berrada",
                            Prenom = "Nadia",
                            SiteRattacheId = 2,
                            Specialites = "Transformateur,TGBT"
                        },
                        new
                        {
                            Id = 4,
                            ChargeActuelle = 0,
                            Disponible = false,
                            Nom = "Mansouri",
                            Prenom = "Youssef",
                            SiteRattacheId = 1,
                            Specialites = "HVAC"
                        },
                        new
                        {
                            Id = 5,
                            ChargeActuelle = 2,
                            Disponible = true,
                            Nom = "Tazi",
                            Prenom = "Othmane",
                            SiteRattacheId = 2,
                            Specialites = "Groupe Électrogène"
                        });
                });

            modelBuilder.Entity("TechnoVIS.Models.Visite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsCorrectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRealisee")
                        .HasColumnType("datetime2");

                    b.Property<int>("DureeEstimeeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<string>("RapportTechnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ScorePriorite")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicienAssigne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeVisite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.ToTable("Visites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionsCorrectives = "",
                            DatePrevue = new DateTime(2026, 8, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeEstimeeMinutes = 120,
                            EquipementId = 1,
                            RapportTechnique = "",
                            Reference = "VIS-2026-1001",
                            ScorePriorite = 65.5,
                            Statut = "Planifiée",
                            TechnicienAssigne = "Amine El Amrani",
                            TypeVisite = "Préventive"
                        },
                        new
                        {
                            Id = 2,
                            ActionsCorrectives = "Remplacement filtre huile et purge système.",
                            DatePrevue = new DateTime(2026, 7, 28, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DureeEstimeeMinutes = 180,
                            EquipementId = 2,
                            RapportTechnique = "Alerte pression huile moteur au démarrage.",
                            Reference = "VIS-2026-1002",
                            ScorePriorite = 92.0,
                            Statut = "En retard",
                            TechnicienAssigne = "Hassan Chraibi",
                            TypeVisite = "Curative"
                        },
                        new
                        {
                            Id = 3,
                            ActionsCorrectives = "Rien à signaler.",
                            DatePrevue = new DateTime(2026, 7, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRealisee = new DateTime(2026, 7, 26, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DureeEstimeeMinutes = 90,
                            EquipementId = 3,
                            RapportTechnique = "Analyse diélectrique huile conforme.",
                            Reference = "VIS-2026-1003",
                            ScorePriorite = 45.0,
                            Statut = "Validée",
                            TechnicienAssigne = "Nadia Berrada",
                            TypeVisite = "Audit"
                        },
                        new
                        {
                            Id = 4,
                            ActionsCorrectives = "",
                            DatePrevue = new DateTime(2026, 8, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DureeEstimeeMinutes = 150,
                            EquipementId = 5,
                            RapportTechnique = "",
                            Reference = "VIS-2026-1004",
                            ScorePriorite = 88.5,
                            Statut = "Planifiée",
                            TechnicienAssigne = "Amine El Amrani",
                            TypeVisite = "Préventive"
                        });
                });

            modelBuilder.Entity("TechnoVIS.Models.Equipement", b =>
                {
                    b.HasOne("TechnoVIS.Models.Site", "Site")
                        .WithMany("Equipements")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("TechnoVIS.Models.Marche", b =>
                {
                    b.HasOne("TechnoVIS.Models.Client", "Client")
                        .WithMany("Marches")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TechnoVIS.Models.Site", b =>
                {
                    b.HasOne("TechnoVIS.Models.Client", "Client")
                        .WithMany("Sites")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TechnoVIS.Models.Technicien", b =>
                {
                    b.HasOne("TechnoVIS.Models.Site", "SiteRattache")
                        .WithMany()
                        .HasForeignKey("SiteRattacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteRattache");
                });

            modelBuilder.Entity("TechnoVIS.Models.Visite", b =>
                {
                    b.HasOne("TechnoVIS.Models.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("TechnoVIS.Models.Client", b =>
                {
                    b.Navigation("Marches");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("TechnoVIS.Models.Site", b =>
                {
                    b.Navigation("Equipements");
                });
#pragma warning restore 612, 618
        }
    }
}
