// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoVIS.Data;

#nullable disable

namespace TechnoVIS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816192925_CleanRealSchema")]
    partial class CleanRealSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnoVIS.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodeClient")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TechnoVIS.Models.Equipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Criticiticite")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateInstallation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DerniereVisite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProchaineVisitePrevue")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScoreRisque")
                        .HasColumnType("int");

                    b.Property<int>("ScoreSante")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("TechnoVIS.Models.Marche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CodeMarche")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentaireImport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipementsDivers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FactureRequise")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreImprimante")
                        .HasColumnType("int");

                    b.Property<int>("NombrePC")
                        .HasColumnType("int");

                    b.Property<int>("NombrePCPortable")
                        .HasColumnType("int");

                    b.Property<int>("NombreServeur")
                        .HasColumnType("int");

                    b.Property<bool>("PvRequis")
                        .HasColumnType("bit");

                    b.Property<int>("SlaHeures")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeContrat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitesAnnuellesPrevues")
                        .HasColumnType("int");

                    b.Property<int>("VisitesRealisees")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CodeMarche")
                        .IsUnique();

                    b.ToTable("Marches");
                });

            modelBuilder.Entity("TechnoVIS.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NomSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CodeSite")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("TechnoVIS.Models.Technicien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargeActuelle")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiteRattacheId")
                        .HasColumnType("int");

                    b.Property<string>("Specialites")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteRattacheId");

                    b.ToTable("Techniciens");
                });

            modelBuilder.Entity("TechnoVIS.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TechnicienId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("TechnoVIS.Models.Visite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsCorrectives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRealisee")
                        .HasColumnType("datetime2");

                    b.Property<int>("DureeEstimeeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<int?>("MarcheId")
                        .HasColumnType("int");

                    b.Property<string>("RapportTechnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ScorePriorite")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicienId")
                        .HasColumnType("int");

                    b.Property<string>("TypeVisite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.HasIndex("MarcheId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("TechnicienId");

                    b.ToTable("Visites");
                });

            modelBuilder.Entity("TechnoVIS.Models.Equipement", b =>
                {
                    b.HasOne("TechnoVIS.Models.Site", "Site")
                        .WithMany("Equipements")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("TechnoVIS.Models.Marche", b =>
                {
                    b.HasOne("TechnoVIS.Models.Client", "Client")
                        .WithMany("Marches")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TechnoVIS.Models.Site", b =>
                {
                    b.HasOne("TechnoVIS.Models.Client", "Client")
                        .WithMany("Sites")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TechnoVIS.Models.Technicien", b =>
                {
                    b.HasOne("TechnoVIS.Models.Site", "SiteRattache")
                        .WithMany()
                        .HasForeignKey("SiteRattacheId");

                    b.Navigation("SiteRattache");
                });

            modelBuilder.Entity("TechnoVIS.Models.Utilisateur", b =>
                {
                    b.HasOne("TechnoVIS.Models.Technicien", "Technicien")
                        .WithMany()
                        .HasForeignKey("TechnicienId");

                    b.Navigation("Technicien");
                });

            modelBuilder.Entity("TechnoVIS.Models.Visite", b =>
                {
                    b.HasOne("TechnoVIS.Models.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnoVIS.Models.Marche", "Marche")
                        .WithMany("Visites")
                        .HasForeignKey("MarcheId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechnoVIS.Models.Technicien", "Technicien")
                        .WithMany("Visites")
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipement");

                    b.Navigation("Marche");

                    b.Navigation("Technicien");
                });

            modelBuilder.Entity("TechnoVIS.Models.Client", b =>
                {
                    b.Navigation("Marches");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("TechnoVIS.Models.Marche", b =>
                {
                    b.Navigation("Visites");
                });

            modelBuilder.Entity("TechnoVIS.Models.Site", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("TechnoVIS.Models.Technicien", b =>
                {
                    b.Navigation("Visites");
                });
#pragma warning restore 612, 618
        }
    }
}
